version: '3.3'

services:
  controller-db:
    container_name: "ban-controller-database"
    image: mysql:5.7
    restart: unless-stopped
    network_mode: "host"
    environment:
      MYSQL_DATABASE: 'ban-controller'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_TCP_PORT: '6606'
    volumes:
      - container-db:/var/lib/mysql
    ports:
      - '6606:6606'
    expose:
      - '6606'

  controller-api:
    build: .
    container_name: "ban-controller-api"
    image: ban-controller:latest
    network_mode: "host"
    restart: unless-stopped
    depends_on:
      - controller-db
    ports:
      - '8888:8888'
    expose:
      - '8888'

volumes:
  container-db:
